export const waxingCollection = [
    {
        title:'顔',
        data:[
            {
                category:'ヒゲ（唇下）',
                price:'2,750',
                discount:'2,200',
            },
            {
                category:'ヒゲ（鼻下）',
                price:'3,300',
                discount:'2,750',
            },
            {
                category:'ヒゲ（あご）',
                price:'4,400',
                discount:'3,300',
            },
            {
                category:'ヒゲ（あご裏）',
                price:'4,400',
                discount:'3,300',
            },
            {
                category:'ヒゲ（両頬）',
                price:'4,400',
                discount:'3,300',
            },
            {
                category:'もみ上げ（左右）',
                price:'4,400',
                discount:'3,300',
            },
            {
                category:'眉（眉間含む）',
                price:'3,300',
                discount:'2,750',
            },
            {
                category:'おでこ',
                price:'3,300',
                discount:'2,750',
            },
            {
                category:'うなじ',
                price:'4,400',
                discount:'3,300',
            },
            {
                category:'首',
                price:'4,400',
                discount:'3,300',
            },
            {
                category:'ヒゲ３カ所セット',
                price:'13,200',
                discount:'12,100',
            },
            {
                category:'顔全体セット',
                price:'16,500',
                discount:'15,400',
            },
            {
                category:'顔全体セット',
                price:'16,500',
                discount:'15,400',
            },
            {
                category:'顔全体セット',
                price:'16,500',
                discount:'15,400',
            },
            {
                category:'≪年間プラン≫　ヒゲ３カ所セット',
                price:'143,000（年額）',
                discount:'132,000（年額）',
            },
        ]
    },
    {
        title:'手足',
        data:[
            {
                category:'手の指（両手）',
                price:'4,400',
                discount:'3,850',
            },
            {
                category:'手の甲（両手）',
                price:'4,400',
                discount:'3,850',
            },
            {
                category:'両手の全体セット',
                price:'6,600',
                discount:'5,500',
            },
            {
                category:'腕ひじ上（両腕）',
                price:'9,900',
                discount:'8,800',
            },
            {
                category:'腕ひじ下（両腕）',
                price:'9,900',
                discount:'8,800',
            },
            {
                category:'両腕の全体セット',
                price:'16,500',
                discount:'14,300',
            },
            {
                category:'太もも（股下～ひざ上：両足）',
                price:'14,300',
                discount:'12,100',
            },
            {
                category:'ひざ下（ひざ含む：両足）',
                price:'14,300',
                discount:'12,100',
            },
            {
                category:'両足付け根～足指までの全体セット',
                price:'23,100',
                discount:'22,000',
            },
            {
                category:'足の指（両足）',
                price:'4,400',
                discount:'3,300',
            },
            {
                category:'足の甲（両足）',
                price:'3,300',
                discount:'2,750',
            },
            {
                category:'両足の指と甲の全体セット',
                price:'5,500',
                discount:'5,500',
            },
        ]
    },
    {
        title:'ボディ',
        data:[
            {
                category:'ワキ（両脇）',
                price:'4,400',
                discount:'3,300',
            },
            {
                category:'肩（両肩）',
                price:'6,600',
                discount:'5,500',
            },
            {
                category:'乳輪周り',
                price:'4,400',
                discount:'3,850',
            },
            {
                category:'胸元',
                price:'12,100',
                discount:'9,900',
            },
            {
                category:'へそ周り',
                price:'4,400',
                discount:'3,850',
            },
            {
                category:'ビキニライン',
                price:'6,600',
                discount:'6,050',
            },
            {
                category:'腹部',
                price:'11,000',
                discount:'9,900',
            },
            {
                category:'腰',
                price:'8,800',
                discount:'7,700',
            },
            {
                category:'お尻（肛門回り除く）',
                price:'8,800',
                discount:'7,700',
            },
            {
                category:'背中',
                price:'7,700',
                discount:'6,600',
            },
            {
                category:'背中全体',
                price:'15,400',
                discount:'13,200',
            },
            {
                category:'首から下全身セット（手足含む）',
                price:'101,200',
                discount:'96,800',
            },
            {
                category:'≪年間プラン≫　首から下全身通い放題',
                price:'1,100,000',
                discount:'990,000',
            },
        ]
    },
]
